CREATE TABLE IF NOT EXISTS admin_users (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS donation_heads (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  minimum_amount NUMERIC(10, 2) NOT NULL DEFAULT 50,
  status VARCHAR(16) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS donations (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  receipt_no VARCHAR(100) NOT NULL,
  order_id VARCHAR(100) NOT NULL,
  transaction_id VARCHAR(150) NULL,
  donor_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  address TEXT NOT NULL,
  head_id INTEGER NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  payment_method VARCHAR(50) NOT NULL,
  payment_status VARCHAR(16) NOT NULL DEFAULT 'Pending',
  gateway VARCHAR(100) NOT NULL DEFAULT 'mock',
  gateway_response JSONB NULL,
  message TEXT NULL,
  receipt_path VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_logs (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  donation_id INTEGER NOT NULL,
  event VARCHAR(100) NOT NULL,
  payload JSONB NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  image VARCHAR(500) NOT NULL DEFAULT '',
  event_date DATE NOT NULL,
  location VARCHAR(255) NOT NULL DEFAULT '',
  status VARCHAR(16) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gallery (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  image VARCHAR(500) NOT NULL,
  category VARCHAR(32) NOT NULL DEFAULT 'Other',
  display_order INTEGER NOT NULL DEFAULT 0,
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(16) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS services (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  short_description VARCHAR(500) NOT NULL,
  image VARCHAR(500) NOT NULL DEFAULT '',
  icon VARCHAR(100) NOT NULL DEFAULT '',
  display_order INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Legacy table retained for compatibility. Confirm the live MySQL schema before production cutover.
CREATE TABLE IF NOT EXISTS payeedetail (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  recno INTEGER NULL,
  headid VARCHAR(50) NULL,
  orderid VARCHAR(100) NULL,
  order_id VARCHAR(100) NULL,
  amount NUMERIC(10, 2) NULL,
  udf1 VARCHAR(255) NULL,
  udf2 VARCHAR(255) NULL,
  udf3 VARCHAR(255) NULL,
  udf4 TEXT NULL,
  name VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  phone VARCHAR(30) NULL,
  mobile VARCHAR(30) NULL,
  address TEXT NULL,
  donor_name VARCHAR(255) NULL,
  head_id VARCHAR(50) NULL,
  payment_status VARCHAR(50) NULL,
  status VARCHAR(50) NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
