CREATE TABLE IF NOT EXISTS events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  image VARCHAR(500) DEFAULT '',
  event_date DATE NOT NULL,
  location VARCHAR(255) NOT NULL,
  status ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS image VARCHAR(500) DEFAULT '',
  ADD COLUMN IF NOT EXISTS event_date DATE NULL,
  ADD COLUMN IF NOT EXISTS location VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS status ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Active',
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE events
SET event_date = `date`
WHERE event_date IS NULL
  AND `date` IS NOT NULL;

ALTER TABLE events
  MODIFY COLUMN event_date DATE NOT NULL;
